### ISSUE TITLE
README points to unaccessible site

### ISSUE THREAD

**Issue by lacostej** [GameAnalytics/GA-Unity-SDK#17]
https://github.com/GameAnalytics/GA-Unity-SDK

points to 

http://support.gameanalytics.com/hc/en-us/articles/200841316-Download-and-setup

which shows:

oops.
You're not authorized to access this page.
Take me back to the home page

**Comment by cristianbercu** [comment]
Thanks for pointing this out. We have a new article http://support.gameanalytics.com/hc/en-us/articles/202770939-Download-and-setup

I will edit the Readme.md file with the new link.
